import { createClient } from '@supabase/supabase-js'

const supabaseUrl = 'https://udiuttnrrwnlksmldleo.supabase.co'
const supabaseAnonKey = 'eeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVkaXV0dG5ycndubGtzbWxkbGVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTY1MDIsImV4cCI6MjA2OTQzMjUwMn0.EMvANZmiGfyfpoKYFr-D4FRvvbOxzwOncCHVR_lDZp4GciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4eGtpcmNvdHZkbWx6anBjb3BmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTY0OTksImV4cCI6MjA2OTQzMjQ5OX0.utZ0oUszU24Qr2C7o05FbCbahlMnm1qnACIYmJqIITw'

export const supabase = createClient(supabaseUrl, supabaseAnonKey)